name: Publish development docs

on:
  push:
    branches:
      - master
      - docs-testing

permissions:
  contents: write

jobs:
  docs:
    name: Development docs release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install poetry
        uses: Gr1N/setup-poetry@v8

      - name: Install dependencies
        run: |
          pip install -U pip
          poetry install

      - name: Build and deploy
        run: |
          git config --global user.name "Jonxslays"
          git config --global user.email "51417989+Jonxslays@users.noreply.github.com"
          git fetch origin gh-pages --depth=1
          poetry run mike deploy --push --update-aliases development development
